### ISSUE TITLE
Issue requesting data

### ISSUE THREAD

**Issue by wouterverduin** [deuxpi/home-assistant-custom-components#5]
Dear Deuxpi,

I dont know if htis is discontinued or anything but i was trying to get it to work.

I set this up in my home assistant and set everything up. When i ran it i got error.

Also attempted to run the python script just with python to get more info. There was an error in line 80:         yield from nokia.async_update()

Is there a way to fix it, am i missing something or is this just discontinued?

Thanks in advance!

**Comment by deuxpi** [comment]
Home Assistant automatically fetches and installs the dependencies for each component. If you try to run the module in a standalone method, you need to manage those dependencies manually.
