### ISSUE TITLE
Nokia Health is now Withings: changes to API

### ISSUE THREAD

**Issue by robmarkcole** [deuxpi/home-assistant-custom-components#7]
Hi you probably received the email below and may need to updated your custom component. 
I mention this in case you are interested in collaborating on making an official integration for HA? I own the scales and sleep monitor.

![image](https://user-images.githubusercontent.com/11855322/46567466-47317380-c92b-11e8-9afb-a810318eb546.png)

**Comment by deuxpi** [comment]
Upgraded the dependencies (python-nokia 1.2.0) and updated the code to support the current OAuth 2 authentication method in https://github.com/deuxpi/home-assistant-custom-components/commit/f05f4d9eeb10149588073f066f23ced2e0c2423c
